export const cities = [
    { ar: 'القاهرة', en: 'Cairo' },
    { ar: 'الإسكندرية', en: 'Alexandria' },
    { ar: 'الجيزة', en: 'Giza' },
    { ar: 'شرم الشيخ', en: 'Sharm El Sheikh' },
    { ar: 'الأقصر', en: 'Luxor' },
    { ar: 'أسوان', en: 'Aswan' },
    { ar: 'بورسعيد', en: 'Port Said' },
    { ar: 'السويس', en: 'Suez' },
    { ar: 'دمياط', en: 'Damietta' },
    { ar: 'المنصورة', en: 'Mansoura' },
    { ar: 'طنطا', en: 'Tanta' },
    { ar: 'الإسماعيلية', en: 'Ismailia' },
    { ar: 'الزقازيق', en: 'Zagazig' },
    { ar: 'أسوان', en: 'Aswan' },
    { ar: 'بنها', en: 'Banha' },
    { ar: 'كفر الشيخ', en: 'Kafr El Sheikh' },
    { ar: 'دمنهور', en: 'Damanhur' },
    { ar: 'المنيا', en: 'Minya' },
    { ar: 'بنى سويف', en: 'Beni Suef' },
    { ar: 'سوهاج', en: 'Sohag' },
    { ar: 'قنا', en: 'Qena' },
    { ar: 'الغردقة', en: 'Hurghada' },
    { ar: 'مرسى مطروح', en: 'Marsa Matruh' },
];