export const apiKeys = {
    auth: {
      register: "/api/v1/auth/register",
      login: "/api/v1/auth/login",
      googleAuth: "/api/v1/auth/googleAuth",
      appleAuth: "/api/v1/auth/appleAuth",
      getUserDetails:"/api/v1/user/details",
      changePassword:"/api/v1/user/changePassword",
      sendCode:"/api/v1/user/sendCode",
      checkCode:"/api/v1/user/checkCode",
      resetPassword:"/api/v1/user/resetPassword",
    },
    stable: {
      addStable: "/api/v1/stable/add",
      login: "/api/v1/stable/login",
      completed: (id:string) => `/api/v1/stable/completed/${id}`,
      getStable: "/api/v1/stable/get",
      stableDetails: "/api/v1/stable/details/",
      stableDetail:(id:string) => `/api/v1/stable/details/${id}`,
      disableStable:(id:string) => `/api/v1/stable/disable/${id}`,

      updateStable:(id:string) => `/api/v1/stable/update/${id}`,
      completeStable:(id:string) => `/api/v1/stable/completed/${id}`,
    },
    horse: {
      addHorse:(stableId:string) => `/api/v1/horse/add/${stableId}`,
      getHorse:(stableId:string) => `/api/v1/horse/get/${stableId}?page=1&nationality=Foreign&service=Ride`,
      horseDetails: "/api/v1/horse/details/",
      horseDetail:(id:string) => `/api/v1/horse/details/${id}`,
      updateHorse: (id:string) => `/api/v1/horse/update/${id}`,
      horseAvailable: "/api/v1/horse/horseAvailable",
      reservedTimes: "/api/v1/horse/reservedTimes",
      deleteHorse:(id:string) => `/api/v1/horse/delete/${id}`,
    },
    event: {
      addEvent: "/api/v1/event/add",
      updateEvent: "/api/v1/event/update",
      deleteEvent: "/api/v1/event/delete",
      booking: "/api/v1/event/booking",
      getEvent: "/api/v1/event/get?page=",
      eventDetails: "/api/v1/event/details/",
    },
    photographer: {
      addPhotographer: "/api/v1/photographer/addPhotographer",
      login: "/api/v1/photographer/login",
      getPhotograoher:"/api/v1/photographer/get",
      getStables:(id:string)=>`/api/v1/photographer/getStables/${id}`,
      completed:(id:string) => `/api/v1/photographer/completed/${id}`,
      getPhotographerDetails:(id:string) => `/api/v1/photographer/get/detail/${id}`,
    },
    school: {
      addSchool: "/api/v1/school/addSchool",
      login: "/api/v1/school/login",
      getSchool:"/api/v1/school/get",
      getSchoolDetail:(id:string) => `/api/v1/school/details/${id}`,
      getStables:(id:string)=>`/api/v1/school/getStables/${id}`,
      completed:(id:string) => `/api/v1/school/completed/${id}`,
      getPhotographerDetails:(id:string) => `/api/v1/school/get/detail/${id}`,
    },

    booking:{
      payment:"/api/v1/payment/pay",
      Photo_session:"/api/v1/booking/create",
      event:"/api/v1/event/booking",
      getBooking:"/api/v1/booking/get",
    },
    refund:{  
      check:(bookingId:string) => `/api/v1/refund/info/${bookingId}`,
      refund:(bookingId:string) => `/api/v1/refund/request/${bookingId}`,
    },
  };