export const navigationEnums = {
  HOME: "home",
  STABLE: "stable",
  SERVICE: "service",
  PROFILE: "profile",
  MAIN: "Main",
  SERIES_STREAM: "series/stream",
  SERIES_DETAILS: "series/details",
  MOVIES: "movies",
  MOVIES_DETAILS: "movies/details",
  MOVIES_STREAM: "movies/stream",
  PROFILE_SETTINGS: "profile/settings",
  PROFILE_PLAYLIST: "profile/playlist",
  PROFILE_LANGUAGE: "profile/language",
  PROFILE_CLEAR_CACHE: "profile/clearCache",
  PROFILE_APPLICATION_INFO: "profile/applicationInfo",

  // Auth
  ONBOARD1: "onboard1",
  ONBOARD2: "onboard2",
  ONBOARD3: "onboard3",
  LOGIN_SCREEN: "login",
  SIGNUP_SCREEN: "signUp",
  FORGET_PASSWORD_SCREEN: "forget-password",
  OTP_SCREEN: "otp",
  CHANGE_PASSWORD_SCREEN: "change-password",
  CHANGE_PASSWORD_SUCCESS_SCREEN: "change-password-success",
  REGISTER_SUCCESS_SCREEN: "register-success",
} as const;